#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu May 12 15:33:07 2022

@author: tommywu
"""

import numpy as np
import pandas as pd 
from sklearn.decomposition import PCA
from scipy import stats
import matplotlib.pyplot as plt
from sklearn.cluster import DBSCAN
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_samples
data = np.genfromtxt('movieReplicationSetQ3.csv',delimiter=',') 
predf=pd.read_csv('movieReplicationSetQ3.csv', header = None)
#%%
meandata=data[1098,0:400]
df1=predf.count()
df1.to_numpy()
df=df1[0:400]

combined=np.column_stack((meandata,df))
sorteddata=combined[combined[:,1].argsort()]

np.median(sorteddata[:,1])

np.mean(sorteddata[0:199,0])
np.mean(sorteddata[199:400,0])

t1,p1=stats.ttest_ind(sorteddata[0:199,0],sorteddata[199:400,0])
