#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat May 14 02:05:08 2022

@author: tommywu
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
from sklearn.decomposition import PCA
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
data = np.genfromtxt('movieReplicationSet.csv',delimiter=',') 
datamean=np.genfromtxt('movieReplicationSetQ3.csv',delimiter=',')
df=pd.read_csv('movieReplicationSet.csv')
#%%
title = df.columns[:400].to_list()
Ftitle= df[title]
index = df.columns[474:477].tolist()
index=df[index]
index = index[~np.isnan(index).any(axis=1)]

modelacurrateQ9=[]
for i in range (400):

    dataset=pd.DataFrame.merge(index,Ftitle[title[i]], left_index =True , right_index = True,how = 'inner')
    dataset.dropna(inplace= True)
    dataset = dataset[~dataset.index.duplicated()]
    lab = preprocessing.LabelEncoder()
    x = dataset.iloc[:,:3]
    y = dataset.iloc[:,3:].to_numpy()
    y_transformed = lab.fit_transform(y) 
    
    clfmodel = RandomForestClassifier(n_estimators=100).fit(x,y_transformed)
    predictions = clfmodel.predict(x)
    print(title[i])
    
    modelAccuracy = accuracy_score(y_transformed,predictions)
    print('Random forest model accuracy:',modelAccuracy)
    modelacurrateQ9.append(modelAccuracy)
    print('---------------')
sum(modelacurrateQ9)/len(modelacurrateQ9)
